One984HOSTING_Username=     # Username
One984HOSTING_Password=		# Password
ACMEDNS_USERNAME=		    # Username. Optional.
ACMEDNS_PASSWORD=		    # Password. Optional.
ACMEDNS_SUBDOMAIN=	        # Subdomain. Optional.
ACMEDNS_BASE_URL=	        # API endpoint. Default: "https://auth.acme-dns.io".
ACMEPROXY_ENDPOINT=	        # API Endpoint
ACMEPROXY_USERNAME=	        # Username
ACMEPROXY_PASSWORD=		    # Password
Active24_ApiKey=		    # API Key. Called "Identifier" in the Active24 Admin
Active24_ApiSecret=		    # API Secret. Called "Secret key" in the Active24 Admin
AD_API_KEY=		            # API Key
Ali_Key=		            # API Key
Ali_Secret=		            # API Secret
Alviy_token=		        # API token. Get it from the https://cloud.alviy.com/token
ANX_Token=		            # API Token
AF_API_USERNAME=		    # API Username
AF_API_PASSWORD=		    # API Password
Arvan_Token=		        # API Token
AURORA_Key=		            # API Key
AURORA_Secret=		        # API Secret
AUTODNS_USER=		        # Username
AUTODNS_PASSWORD=		    # Password
AUTODNS_CONTEXT=		    # Context
AWS_ACCESS_KEY_ID=		    # API Key ID
AWS_SECRET_ACCESS_KEY=		# API Secret
AZION_Email=		        # Email
AZION_Password=		        # Password
AZUREDNS_SUBSCRIPTIONID=	# Subscription ID
AZUREDNS_TENANTID=		    # Tenant ID
AZUREDNS_APPID=		        # App ID. App ID of the service principal
AZUREDNS_CLIENTSECRET=		# Client Secret. Secret from creating the service principal
AZUREDNS_MANAGEDIDENTITY=	# Use Managed Identity. Use Managed Identity assigned to a resource instead of a service principal. "true"/"false"
AZUREDNS_BEARERTOKEN=		# Bearer Token. Used instead of service principal credentials or managed identity. Optional.
BEGET_User=		            # API user
BEGET_Password=             # API password
BOOKMYNAME_USERNAME=		# Username
BOOKMYNAME_PASSWORD=		# Password
BUNNY_API_KEY=		        # API Key
CF_Key=		                # API Key
CF_Email=		            # Your account email
CF_Token=		            # API Token
CF_Account_ID=		        # Account ID
CF_Zone_ID=		            # Zone ID. Optional.
CLOUDDNS_EMAIL=		        # Email
CLOUDDNS_PASSWORD=		    # Password
CLOUDDNS_CLIENT_ID=		    # Client ID
CLOUDNS_AUTH_ID=		    # Regular auth ID
CLOUDNS_SUB_AUTH_ID=		# Sub auth ID
CLOUDNS_AUTH_PASSWORD=		# Auth Password
CN_User=		            # User
CN_Password=		        # Password
CONOHA_Username=		    # Username
CONOHA_Password=		    # Password
CONOHA_TenantId=		    # TenantId
CONOHA_IdentityServiceApi=	# Identity Service API. E.g. "https://identity.xxxx.conoha.io/v2.0"
CONSTELLIX_Key=		        # API Key
CONSTELLIX_Secret=		    # API Secret
cPanel_Username=		    # Username
cPanel_Apitoken=		    # API Token
cPanel_Hostname=		    # Server URL. E.g. "https://hostname:port"
CURANET_AUTHCLIENTID=		# Auth ClientID. Requires scope dns
CURANET_AUTHSECRET=		    # Auth Secret
CY_Username=		        # Username
CY_Password=		        # API Token
CY_OTP_Secret=		        # OTP token. Only required if using 2FA
DA_Api=		                # API Server URL. E.g. "https://remoteUser:remotePassword@da.domain.tld:8443"
DA_Api_Insecure=		    # Insecure TLS. 0: check for cert validity, 1: always accept
DDNSS_Token=		        # API Token
# desec
DEDYN_TOKEN=		        # API Token
DF_user=		            # Username
DF_password=		        # Password
 # dgon | DigitalOcean
DO_API_KEY=		            # API Key
  # dnsexit
DNSEXIT_API_KEY=		    # API Key
DNSEXIT_AUTH_USER=		    # Username
DNSEXIT_AUTH_PASS=		    # Password
 # dnshome
DNSHOME_Subdomain=		    # Subdomain
DNSHOME_SubdomainPassword=	# Subdomain Password
 # hetzner
HETZNER_Token=		        # API Token
